name: Run tests

on: [push]

jobs:
  tests:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest numpy scipy
      - name: Test with pytest
        run: |
          ls -a
          pytest example.py
      - uses: actions/upload-artifact@v2
        with:
          name: WAV Files
          path: ./wavs